### ISSUE TITLE
著作権表記について

### ISSUE THREAD

**Issue by kiyoshiiriemon** [rsasaki0109/PoseOptimizationSLAM3D#1]
MPL2.0 http://mozilla.org/MPL/2.0/ 
には下記の条項がありますのでご確認をお願いします．

3.4. Notices

You may not remove or alter the substance of any license notices
(including copyright notices, patent notices, disclaimers of warranty,
or limitations of liability) contained within the Source Code Form of
the Covered Software, except that You may alter any license notices to
the extent required to remedy known factual inaccuracies.

**Comment by rsasaki0109** [comment]
ご指摘ありがとうございます。
プログラムのヘッダー部に著作権を表記致しました。

**Comment by kiyoshiiriemon** [comment]
ご対応ありがとうございます．
