### ISSUE TITLE
a problem in 'def dR_dRV(self, rv)'

### ISSUE THREAD

**Issue by zhchyang2004** [rsasaki0109/PoseOptimizationSLAM3D#2]
Hi, the partial derivative dRdqz should be as follows:

dRdqz = 2 * np.array(
            [[-qz, -qw, qx],
             [qw, -qz, qy], 
             [qx, qy, qz]]  

Do you think so?

**Comment by rsasaki0109** [comment]
Yes, that's right.
Thank you for pointing it out.
I've fixed it.
https://github.com/rsasaki0109/PoseOptimizationSLAM3D/commit/6691947118303bee98796dce3df78d133000b63e
